# Site settings
author: John Ajaka
title: John Ajaka
header-img: img/home-bg.png
email: johnajaka96@gmail.com
copyright_name: John Ajaka
description: > # this means to ignore newlines until "baseurl:"
  Future Coders Journey
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  JohnAjaka

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
